rust_library(
    name = "volo-gen",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    visibility = ["PUBLIC"],
    deps = [
        "root//third-party/rust:anyhow",
        "root//third-party/rust:futures",
        "root//third-party/rust:pilota",
        "root//third-party/rust:tokio",
        "root//third-party/rust:volo",
        "root//third-party/rust:volo-grpc",
    ],
)
