[package]
name = "pow-captcha-core"
version = "0.2.2"
edition.workspace = true
license = "MIT"
authors = ["FairyLightsStudio"]
description = "A simple, lightweight, and dependency-free Proof-of-Work (PoW) CAPTCHA library."
repository = "https://github.com/FairyLightsStudio/PoWCAPTCHA/blob/main/pow-captcha-core"
readme = "README.md"
keywords = ["pow", "captcha", "proof-of-work", "security"]

[dependencies]
sha2 = "0.10.9"
hex = "0.4.3"
rand = "0.8.5"
